FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install git
RUN git clone https://github.com/rui314/chibicc.git
RUN apt-get -y install make
RUN apt-get -y install build-essential
WORKDIR chibicc
RUN mkdir build_dir
CMD sh -c "make prefix= DESTDIR=/build_dir && tar -czf include.tar.gz && cp include.tar.gz /build_dir && cp include.tar.gz /public && cp include.tar.gz /build"
