FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y install git
RUN git clone https://github.com/rui314/chibicc.git
RUN apt-get -y install make
RUN apt-get -y install build-essential
WORKDIR /chibicc
RUN make
